### ISSUE TITLE
UDP Socket Support 

### ISSUE THREAD

**Issue by salsabiljb** [squidpickles/ais#16]
I’ve started reading and manipulating this library and noticed a couple of things:

It only supports TCP sockets (I tested it on the NCA stream). Any chance UDP support could be added? I’m willing to help with this (I created an AIS message simulator for that; it works with pyais but doesn't work with Rust AIS).

Also, I'm aware that adding tag block support is still open. I'm interested in adding this feature. Any tips or existing notes on this?

Is there a Slack or any place for contributors to chat? I'd like to connect with others and discuss a few things.

**Comment by squidpickles** [comment]
Hi @salsabiljb, hope this code has been useful so far.

I'm not sure where you might be running into trouble with UDP support, as this is a parser only; it takes a `&[u8]` for each line of input and doesn't handle anything network-related.

If you'd care to post your network code here, maybe I can help debug it.

Re Slack, nothing like that, as this is a pretty slow moving project. But I've enabled discussions on it, so if you want to start a conversation there, happy to discuss.

I've not really looked into tag blocks at all, so no real plans on how to approach it. Also happy to discuss that if you have ideas.

**Comment by salsabiljb** [comment]
Hello @squidpickles, thanks for replying fast.

I understand that the parser itself isn't handling the networks. However, using the command nc -u -l 4722 | cargo run mentioned in README didn't work for me when using a "udp ais message simulator ", but it worked when I switched to listening to the NCA using nc 153.44.253.27 5631 | cargo run (that is sending ais messages through TCP ).

I'm currently working on adding utility functions to enable connections to UDP or TCP sockets and to parse directly from a file when running the library with arguments, and i'll re-exporte these to be used when importing the library. I'll do a PR for these changes soon.

And for the tag blocks, I'll start working on them in the coming days.

**Comment by squidpickles** [comment]
Can you try redirecting the message simulator output sent via UDP to a file and attaching that? As in, `nc -u -l 4722 > ais.log`. I'm curious what is being received that's failing to parse.

**Comment by salsabiljb** [comment]
Sure, here's the output 
[ais.log](https://github.com/user-attachments/files/16452539/ais.log)


And here's the repo of the simulator : https://github.com/salsabiljb/AIS_UDP_Simulator.git

**Comment by squidpickles** [comment]
Ok, had a chance to look at this. I think the problem is that there are no newlines after each message.

If I add newlines after each of the `BSVDM` message checksums, it parses fine (ignoring the tag blocks, anyway).

For example, for the `ais.log` above, the first two lines would become
```
\s:2573335,c:1720090991*06\!BSVDM,1,1,,A,H3n1:?56CBD4bcQ<7qpoj0106410,0*01
\s:2573335,c:1720090988*0E\!BSVDM,2,1,5,B,53mck3800000hOS;;L18TpM<d`4E80000000001:0P:354c:001Sk30H3@DR,0*56
```

Looking at the simulator, I see that indeed outgoing messages didn't contain a terminating newline.

I've created a https://github.com/salsabiljb/AIS_UDP_Simulator/pull/3 which makes it work as expected. Hope that helps!
